food_list = ["Meat / Beef",
"Meat / Bison",
"Meat / Buffalo",
"Meat / Chicken",
"Meat / Duck",
"Meat / Geese / goose",
"Meat / Lamb",
"Meat / Mutton",
"Meat / Ostrich",
"Meat / Pork",
"Meat / Turkey",
"Meat / Veal",
"Meat / Game / Partridge",
"Meat / Game / Pheasant",
"Meat / Game / Rabbit",
"Meat / Game / Hare / levret",
"Meat / Game / Venison",
"Meat / Processed meat / Bacon",
"Meat / Processed meat / Burgers",
"Meat / Processed meat / Cured meat",
"Meat / Processed meat / Gelatins",
"Meat / Processed meat / Haggis",
"Meat / Processed meat / Ham",
"Meat / Processed meat / Lunch meat",
"Meat / Processed meat / Meat Pies",
"Meat / Processed meat / Meatballs / Faggots",
"Meat / Processed meat / Mincemeat",
"Meat / Processed meat / Pasties",
"Meat / Processed meat / Pate",
"Meat / Processed meat / Pork Pies",
"Meat / Processed meat / Sausages",
"Meat / Processed meat / Scotch Eggs",
"Meat / Processed meat / Smoked Duck / Chicken",
"Meat / Processed meat / Spiced Chicken",
"Fish / Bass",
"Fish / Bream",
"Fish / Cod",
"Fish / Haddock",
"Fish / Mackerel",
"Fish / Salmon",
"Fish / Trout",
"Fish / Salmon",
"Fish / Mackerel",
"Fish / Trout",
"Fish / American Shad",
"Fish / American Sole",
"Fish / Anchovy",
"Fish / Antarctic Cod",
"Fish / Arrowtooth Eel",
"Fish / Asian Carps",
"Fish / Atka Mackerel",
"Fish / Atlantic Bonito",
"Fish / Atlantic Cod",
"Fish / Atlantic Eel",
"Fish / Atlantic Herring",
"Fish / Atlantic Salmon",
"Fish / Atlantic Trout",
"Fish / Australasian Salmon",
"Fish / Bar Jack",
"Fish / Bat Fish",
"Fish / Barramundi",
"Fish / Basa Fish",
"Fish / Black Mackerel",
"Fish / Blue Cod",
"Fish / Bluegill",
"Fish / Bluefish",
"Fish / Bombay Duck",
"Fish / Brook Trout",
"Fish / Butterfish",
"Fish / California Halibut",
"Fish / California Sheephead",
"Fish / Capelin",
"Fish / Carp",
"Fish / Catfish",
"Fish / Cherry Salmon",
"Fish / Chinook Salmon",
"Fish / Chum Salmon",
"Fish / Cobia",
"Fish / Cod",
"Fish / Coho Salmon",
"Fish / Coley",
"Fish / Common Carp",
"Fish / Crappie",
"Fish / Crawfish",
"Fish / Dory",
"Fish / Discus",
"Fish / Drum",
"Fish / Dino",
"Fish / Eel",
"Fish / European Eel",
"Fish / European Flounder",
"Fish / Flathead",
"Fish / Flatfish",
"Fish / Flounder",
"Fish / Freshwater Eel",
"Fish / Freshwater Herring",
"Fish / Flying Fish",
"Fish / Giant Gourami",
"Fish / Gilt-head Bream",
"Fish / Golden Dorado",
"Fish / Groundfish",
"Fish / Grouper",
"Fish / Gar",
"Fish / Haddock",
"Fish / Hake",
"Fish / Halibut",
"Fish / Harvestfish",
"Fish / Herring",
"Fish / Hilsa",
"Fish / Hoki",
"Fish / Iridescent Shark / Basa Fish",
"Fish / Japanese Butterfish",
"Fish / John Dory",
"Fish / Kapenta",
"Fish / Kingklip",
"Fish / Lemon Sole",
"Fish / Largemouth Bass",
"Fish / Mackerel",
"Fish / Maori Cod",
"Fish / Mahi-mahi",
"Fish / Marlin",
"Fish / Milkfish",
"Fish / Monkfish",
"Fish / Mullet",
"Fish / Mullus Surmuletus",
"Fish / Northern Anchovy",
"Fish / Northern Pike",
"Fish / Northern Snakehead",
"Fish / Norwegian Atlantic Salmon",
"Fish / Orange Roughy",
"Fish / Oscar",
"Fish / Pacific Herring",
"Fish / Pacific Salmon",
"Fish / Pacific Saury",
"Fish / Pacific Trout",
"Fish / Panfish",
"Fish / Pangasius",
"Fish / Patagonian Toothfish",
"Fish / Pelagic Cod",
"Fish / Perch",
"Fish / Pink Salmon",
"Fish / Pollock",
"Fish / Pomfret",
"Fish / Pilchard",
"Fish / Paddlefish",
"Fish / Plaice",
"Fish / Pacific Cod",
"Fish / Quoy Fish",
"Fish / Rainbow Trout",
"Fish / Redfish",
"Fish / Red Snapper",
"Fish / Rock Fish",
"Fish / Round Herring",
"Fish / Salmon",
"Fish / Sardine",
"Fish / Saury",
"Fish / Scrod",
"Fish / Sea Bass",
"Fish / Seer Fish",
"Fish / Shad",
"Fish / Shrimpfish",
"Fish / Silver Carp",
"Fish / Skipjack Tuna",
"Fish / Slender Rainbow Sardine",
"Fish / Sole",
"Fish / Snakeskin Gourami",
"Fish / Snapper",
"Fish / Snook",
"Fish / Snoek",
"Fish / Spanish Mackerel",
"Fish / Surf Sardine",
"Fish / Swamp-eel",
"Fish / Swordfish",
"Fish / Skate",
"Fish / Sunfish  Bluegill",
"Fish / Smallmouth Bass",
"Fish / Spoonbill / Paddlefish",
"Fish / Thresher Shark",
"Fish / Tilapia",
"Fish / Tilefish",
"Fish / Trout",
"Fish / Tuna",
"Fish / Turbot",
"Fish / Yellowfin Tuna",
"Fish / Zander",
"Fish / Caviar",
"Fish / Roe (cod)",
"Fish / Processed Fish / Fishcakes",
"Fish / Processed Fish / Fishpie",
"Fish / Processed Fish / Fishfingers",
"Fish / Processed Fish / Sushi",
"Shellfish / Prawns",
"Shellfish / Oysters",
"Shellfish / Lobster",
"Shellfish / Clams",
"Shellfish / Crabs",
"Shellfish / Shrimp",
"Shellfish / Cockles",
"Shellfish / Mussels",
"Shellfish / Scallops",
"Shellfish / Whelks",
"Shellfish / Winkles",
"Dairy / Butter",
"Dairy / Cream / Clotted cream",
"Dairy / Cream / Single cream",
"Dairy / Cream / Double cream",
"Dairy / Milk / Cow's milk",
"Dairy / Milk / Goat's milk",
"Dairy / Cheese / Chedder",
"Dairy / Cheese / Goat",
"Dairy / Cheese / Brie",
"Dairy / Cheese / Stilton",
"Dairy / Cheese /",
"Dairy / Cheese / Blue cheese / Bath Blue cheese",
"Dairy / Cheese / Blue cheese / Barkham Blue cheese",
"Dairy / Cheese / Blue cheese / Blue Monday cheese",
"Dairy / Cheese / Blue cheese / Buxton Blue cheese",
"Dairy / Cheese / Blue cheese / Cheshire Blue cheese",
"Dairy / Cheese / Blue cheese / Devon Blue cheese",
"Dairy / Cheese / Blue cheese / Dorset Blue Vinney cheese",
"Dairy / Cheese / Blue cheese / Dovedale cheese",
"Dairy / Cheese / Blue cheese / Exmoor Blue cheese",
"Dairy / Cheese / Blue cheese / Harbourne Blue cheese",
"Dairy / Cheese / Blue cheese / Lanark Blue  cheese",
"Dairy / Cheese / Blue cheese / Oxford Blue cheese",
"Dairy / Cheese / Blue cheese / Shropshire Blue cheese",
"Dairy / Cheese / Blue cheese / Stichelton cheese",
"Dairy / Cheese / Blue cheese / Stilton cheese",
"Dairy / Cheese / Blue cheese / Blue Wensleydale cheese",
"Dairy / Cheese / Blue cheese / Yorkshire Blue cheese",
"Dairy / Cheese / Appledore cheese",
"Dairy / Cheese / Berkswell cheese",
"Dairy / Cheese / Bonchester cheese",
"Dairy / Cheese / Brie cheese",
"Dairy / Cheese / Somerset Brie",
"Dairy / Cheese / Cornish Brie cheese",
"Dairy / Cheese / Brinkburn cheese",
"Dairy / Cheese / Caithness cheese",
"Dairy / Cheese / Caboc cheese",
"Dairy / Cheese / Caerphilly cheese",
"Dairy / Cheese / Cheddar cheese",
"Dairy / Cheese / West Country Farmhouse Cheddar cheese",
"Dairy / Cheese / Applewood cheese",
"Dairy / Cheese / Coleraine Cheddar cheese",
"Dairy / Cheese / Cheshire cheese",
"Dairy / Cheese / Appleby Cheshire cheese",
"Dairy / Cheese / Chevington cheese",
"Dairy / Cheese / Coquetdale cheese",
"Dairy / Cheese / Cornish Pepper cheese",
"Dairy / Cheese / Cotherstone cheese",
"Dairy / Cheese / Cotswold cheese",
"Dairy / Cheese / Coverdale cheese",
"Dairy / Cheese / Croglin cheese",
"Dairy / Cheese / Crowdie cheese",
"Dairy / Cheese / Derby cheese",
"Dairy / Cheese / Double Gloucester cheese",
"Dairy / Cheese / Goosnargh Gold cheese",
"Dairy / Cheese / Dorstone cheese",
"Dairy / Cheese / Dovedale cheese",
"Dairy / Cheese / Farmhouse Llanboidy cheese",
"Dairy / Cheese / Fine Fettle Yorkshire cheese",
"Dairy / Cheese / Black Eyed Susan cheese",
"Dairy / Cheese / Golden Cross cheese",
"Dairy / Cheese / Gruth Dhu cheese",
"Dairy / Cheese / Harlech cheese",
"Dairy / Cheese / Hereford Hop cheese",
"Dairy / Cheese / Huntsman cheese",
"Dairy / Cheese / Ilchester cheese",
"Dairy / Cheese / Innkeepers Choice cheese",
"Dairy / Cheese / Isle Of Mull cheese",
"Dairy / Cheese / Lancashire cheese",
"Dairy / Cheese / Beacon Fell Traditional Lancashire cheese",
"Dairy / Cheese / Lincolnshire Poacher cheese",
"Dairy / Cheese / Little Wallop cheese",
"Dairy / Cheese / Katy's White Lavender cheese",
"Dairy / Cheese / Kidderton Ash cheese",
"Dairy / Cheese / Lord Of The Hundreds cheese",
"Dairy / Cheese / Lowerdale Goats Cheese cheese",
"Dairy / Cheese / Pantysgawn cheese",
"Dairy / Cheese / Red Devil cheese",
"Dairy / Cheese / Red Dragon cheese",
"Dairy / Cheese / Red Leicester cheese",
"Dairy / Cheese / Rothbury Red cheese",
"Dairy / Cheese / Red Windsor cheese",
"Dairy / Cheese / Sage Derby cheese",
"Dairy / Cheese / Single Gloucester cheese",
"Dairy / Cheese / Stinking Bishop cheese",
"Dairy / Cheese / Sussex Slipcote cheese",
"Dairy / Cheese / Swaledale cheese",
"Dairy / Cheese / Teviotdale  cheese",
"Dairy / Cheese / Tintern cheese",
"Dairy / Cheese / Waterloo cheese",
"Dairy / Cheese / Wensleydale cheese",
"Dairy / Cheese / White Stilton cheese",
"Dairy / Cheese / Suffolk Gold cheese",
"Dairy / Cheese / Whitehaven cheese",
"Dairy / Cheese / Yarg cheese",
"Dairy / Cheese / Wild Garlic Yarg cheese",
"Dairy / Cheese / Wiltshire Loaf",
"Dairy / Cheese / Woolsery Goats cheese",
"Dairy / Cheese / Village Green Goat",
"Dairy / Cheese / Y Fenni cheese",
"Dairy / Ice Cream / Sorbets",
"Dairy / Yoghurt",
"Eggs / Chicken",
"Eggs / Duck",
"Eggs / Quails",
"Eggs / Goose / geese",
"Eggs / Turkey",
"Fruit / Apples   ",
"Fruit / Apricots",
"Fruit / Bananas",
"Fruit / Bilberry",
"Fruit / Blackberries",
"Fruit / Blackcurrants",
"Fruit / Blueberries",
"Fruit / Cherimoya",
"Fruit / Cherries",
"Fruit / Clementine",
"Fruit / Coconuts",
"Fruit / Cranberries",
"Fruit / Currant",
"Fruit / Damson",
"Fruit / Dates",
"Fruit / Dragon fruit",
"Fruit / Durians ",
"Fruit / Elderberry",
"Fruit / Feijoa",
"Fruit / Fig",
"Fruit / Gooseberries",
"Fruit / Gooseberry",
"Fruit / Grape",
"Fruit / Grapefruit",
"Fruit / Grapes",
"Fruit / Guava",
"Fruit / Honeydew melon",
"Fruit / Huckleberry",
"Fruit / Jack fruit ",
"Fruit / Jambul",
"Fruit / Kiwi fruit",
"Fruit / Kumquat",
"Fruit / Legume",
"Fruit / Lemon  ",
"Fruit / Limes",
"Fruit / Lychee",
"Fruit / Mandarine",
"Fruit / Mango  ",
"Fruit / Mangostine",
"Fruit / Medlar",
"Fruit / Melon / cantaloupe",
"Fruit / Nectarines",
"Fruit / Oranges",
"Fruit / Papaya",
"Fruit / Peach",
"Fruit / Pears",
"Fruit / Physalis",
"Fruit / Pineapple",
"Fruit / Pitaya",
"Fruit / Plum, prune",
"Fruit / Pomegranates",
"Fruit / Prunes",
"Fruit / Quince ",
"Fruit / Raisins",
"Fruit / Rambutan",
"Fruit / Raspberries ",
"Fruit / Redcurrants",
"Fruit / Rhubarb",
"Fruit / Salal berry",
"Fruit / Satsuma",
"Fruit / Star fruit",
"Fruit / Strawberries ",
"Fruit / Tangerines",
"Fruit / Ugli fruit ",
"Fruit / Watermelon  ",
"Fruit / Processed fruits / Canned fruit",
"Fruit / Processed fruits / Frozen fruit",
"Fruit / Processed fruits / Fruit sauces",
"Fruit / Processed fruits / Jam",
"Fruit / Processed fruits / Pie fillings",
"Vegetables / Artichokes / Jerusalem",
"Vegetables / Artichokes / Globe ",
"Vegetables / Aubergine",
"Vegetables / Alfalfa sprouts",
"Vegetables / Anise",
"Vegetables / Artichoke",
"Vegetables / Arugula",
"Vegetables / Asparagus",
"Vegetables / Aubergine, Eggplant",
"Vegetables / Avocados ",
"Vegetables / Beansprouts",
"Vegetables / Bell pepper",
"Vegetables / Beetroot, Beet",
"Vegetables / Breadfruit",
"Vegetables / Broccoflower ",
"Vegetables / Broccoli / Purple Sprouting Broccoli",
"Vegetables / Brussels sprouts",
"Vegetables / Cabbage / Red",
"Vegetables / Cabbage / White",
"Vegetables / Cabbage / Green ",
"Vegetables / Calabrese ",
"Vegetables / Celeriac",
"Vegetables / Chinese leaves, Bok choy",
"Vegetables / Collard greens",
"Vegetables / Corn salad",
"Vegetables / Carrots",
"Vegetables / Cauliflflower",
"Vegetables / Celery",
"Vegetables / Chard ",
"Vegetables / Cucumbers ",
"Vegetables / Crimini",
"Vegetables / Daikon",
"Vegetables / Endive",
"Vegetables / Fennel ",
"Vegetables / Fiddlehead fern",
"Vegetables / Frisee leaves",
"Vegetables / Garlic",
"Vegetables / Jicama",
"Vegetables / Kale / Curly kale",
"Vegetables / Kale / Mixed kale",
"Vegetables / Kohlrabi",
"Vegetables / Leeks",
"Vegetables / Lettuce / Romaine",
"Vegetables / Lettuce / Iceberg",
"Vegetables / Marrow",
"Vegetables / Mushrooms / Shiitake mushrooms",
"Vegetables / Mushrooms / Truffles",
"Vegetables / Mushrooms / Boletus mushrooms",
"Vegetables / Mushrooms / Oyster mushrooms",
"Vegetables / Mushrooms / Wild mushrooms",
"Vegetables / Mushrooms / Button mushrooms",
"Vegetables / Mustard greens",
"Vegetables / Nettles ",
"Vegetables / Okra",
"Vegetables / Olives",
"Vegetables / Onions",
"Vegetables / Pakchoi",
"Vegetables / Parsnips",
"Vegetables / Potatoes / Charlotte potatoes",
"Vegetables / Potatoes / King Edward potatoes",
"Vegetables / Potatoes / Estima potatoes",
"Vegetables / Potatoes / Maris Piper potatoes",
"Vegetables / Potatoes / Desiree potatoes",
"Vegetables / Potatoes / Marfona potatoes",
"Vegetables / Potatoes / Anya potatoes",
"Vegetables / Potatoes / Nicola potatoes",
"Vegetables / Potatoes / Rooster potatoes",
"Vegetables / Potatoes / Sante potatoes",
"Vegetables / Potatoes / Accord potatoes",
"Vegetables / Potatoes / Carlingford potatoes",
"Vegetables / Potatoes / Romano potatoes",
"Vegetables / Potatoes / Sweet potatoes, yams",
"Vegetables / Rocket",
"Vegetables / Radicchio",
"Vegetables / Radish",
"Vegetables / Rhubarb",
"Vegetables / Salad",
"Vegetables / Salad Packs",
"Vegetables / Salsify ",
"Vegetables / Savoy Cabbage",
"Vegetables / Sea Vegetables ",
"Vegetables / Shallots",
"Vegetables / Skirret ",
"Vegetables / Spinach",
"Vegetables / Spring Greens ",
"Vegetables / Spring onions, Green onion, Scallion",
"Vegetables / Sprouted Seeds ",
"Vegetables / Squashes / Acorn squash",
"Vegetables / Squashes / Butternut squash",
"Vegetables / Squashes / Courgette, Zucchini",
"Vegetables / Squashes / Cucumber ",
"Vegetables / Squashes / Gem squash",
"Vegetables / Squashes / Marrow, Squash",
"Vegetables / Squashes / Pumpkin",
"Vegetables / Squashes / Spaghetti squash",
"Vegetables / Swede, Rutabaga",
"Vegetables / Sweetcorn, maize, corn",
"Vegetables / Swiss Chard",
"Vegetables / Taro ",
"Vegetables / Tat soi",
"Vegetables / Tomatoes",
"Vegetables / Turnips",
"Vegetables / Turnip Greens ",
"Vegetables / Watercress  ",
"Vegetables / Wasabi",
"Vegetables / Water chestnut",
"Vegetables / White radish",
"Vegetables / Processed vegetables / Canned vegetables",
"Vegetables / Processed vegetables / Frozen vegetables",
"Vegetables / Processed vegetables / French fries",
"Beans & Legumes / Azuki beans, Adzuki beans",
"Beans & Legumes / Bean sprouts",
"Beans & Legumes / Black beans",
"Beans & Legumes / Black-eyed peas",
"Beans & Legumes / Borlotti beans",
"Beans & Legumes / Broad beans",
"Beans & Legumes / Butter Beans",
"Beans & Legumes / Chickpeas, Garbanzo beans, Ceci beans",
"Beans & Legumes / Dried Peas",
"Beans & Legumes / Green beans",
"Beans & Legumes / Kidney beans",
"Beans & Legumes / Lentils",
"Beans & Legumes / Lima bean, Butter bean",
"Beans & Legumes / Miso",
"Beans & Legumes / Mung beans",
"Beans & Legumes / Navy beans",
"Beans & Legumes / Peas / Mangetout, Sugar snap peas",
"Beans & Legumes / Pinto beans",
"Beans & Legumes / Runner beans",
"Beans & Legumes / Soy beans",
"Beans & Legumes / Soybeans",
"Beans & Legumes / Tempeh",
"Beans & Legumes / Tofu",
"Beans & Legumes / Vigna Beans",
"Nuts, Seeds & Oils / Almonds",
"Nuts, Seeds & Oils / Apricot Kernels",
"Nuts, Seeds & Oils / Betel Nuts",
"Nuts, Seeds & Oils / Brazil Nuts",
"Nuts, Seeds & Oils / Cashews",
"Nuts, Seeds & Oils / Chestnuts",
"Nuts, Seeds & Oils / Flaxseeds",
"Nuts, Seeds & Oils / Ginkgo Nuts",
"Nuts, Seeds & Oils / Hazelnuts",
"Nuts, Seeds & Oils / Macadamia Nuts",
"Nuts, Seeds & Oils / Melon Seeds",
"Nuts, Seeds & Oils / Olive Oil",
"Nuts, Seeds & Oils / Peanuts",
"Nuts, Seeds & Oils / Pecan Nuts",
"Nuts, Seeds & Oils / Pine Nuts",
"Nuts, Seeds & Oils / Pistachio Nuts",
"Nuts, Seeds & Oils / Pumpkin Seeds",
"Nuts, Seeds & Oils / Sesame Seeds",
"Nuts, Seeds & Oils / Sunflower Kernels",
"Nuts, Seeds & Oils / Sunflower Seeds",
"Nuts, Seeds & Oils / Walnuts",
"Herbs & Spices / Ajwain, carom seeds",
"Herbs & Spices / Akudjura",
"Herbs & Spices / Alexanders",
"Herbs & Spices / Allspice",
"Herbs & Spices / Angelica",
"Herbs & Spices / Anise",
"Herbs & Spices / Aniseed myrtle",
"Herbs & Spices / Annatto",
"Herbs & Spices / Apple mint",
"Herbs & Spices / Arrowroot starch",
"Herbs & Spices / Avocado leaf",
"Herbs & Spices / Barberry",
"Herbs & Spices / Basil",
"Herbs & Spices / Bay leaf",
"Herbs & Spices / Black cardamom",
"Herbs & Spices / Boldo",
"Herbs & Spices / Borage",
"Herbs & Spices / Calendula, pot marigold",
"Herbs & Spices / Camphor laurel",
"Herbs & Spices / Caraway",
"Herbs & Spices / Cardamom",
"Herbs & Spices / Carob",
"Herbs & Spices / Cassia",
"Herbs & Spices / Catnip",
"Herbs & Spices / Celery seed",
"Herbs & Spices / Chervil",
"Herbs & Spices / Chicory",
"Herbs & Spices / Chili powder",
"Herbs & Spices / Chives",
"Herbs & Spices / Cicely",
"Herbs & Spices / Cilantro, coriander greens, coriander herb",
"Herbs & Spices / Cinnamon",
"Herbs & Spices / Cinnamon myrtle",
"Herbs & Spices / Clary, Clary sage",
"Herbs & Spices / Cloves",
"Herbs & Spices / Coriander",
"Herbs & Spices / Coriander seed",
"Herbs & Spices / Costmary",
"Herbs & Spices / Cream of tartar",
"Herbs & Spices / Cudweed",
"Herbs & Spices / Cumin",
"Herbs & Spices / Cumin Seeds",
"Herbs & Spices / Curry leaf",
"Herbs & Spices / Curry plant",
"Herbs & Spices / Curry powder",
"Herbs & Spices / Dill",
"Herbs & Spices / Dill seed",
"Herbs & Spices / Elderflower",
"Herbs & Spices / Epazote",
"Herbs & Spices / Fennel",
"Herbs & Spices / Fennel seeds",
"Herbs & Spices / Fenugreek",
"Herbs & Spices / File powder, gumbo file",
"Herbs & Spices / Fingerroot, krachai, temu kuntji",
"Herbs & Spices / Five-spice powder ",
"Herbs & Spices / Galingale",
"Herbs & Spices / Garlic / Garlic powder",
"Herbs & Spices / Garlic / Elephant garlic",
"Herbs & Spices / Garlic chives",
"Herbs & Spices / Ginger",
"Herbs & Spices / Golpar, Persian hogweed",
"Herbs & Spices / Grains of paradise",
"Herbs & Spices / Horseradish",
"Herbs & Spices / Houttuynia cordata",
"Herbs & Spices / Huacatay, Mexican marigold, mint marigold",
"Herbs & Spices / Hyssop",
"Herbs & Spices / Jasmine flowers",
"Herbs & Spices / Jimbu",
"Herbs & Spices / Juniper berry",
"Herbs & Spices / Kaffir lime leaves, Makrud lime leaves",
"Herbs & Spices / Kala zeera , black cumin",
"Herbs & Spices / Kawakawa seeds",
"Herbs & Spices / Keluak, kluwak, kepayang",
"Herbs & Spices / Kencur, galangal, kentjur",
"Herbs & Spices / Kokam seed",
"Herbs & Spices / Korarima, Ethiopian cardamom, false cardamon",
"Herbs & Spices / Koseret leaves",
"Herbs & Spices / Lavender",
"Herbs & Spices / Lemon balm",
"Herbs & Spices / Lemon ironbark",
"Herbs & Spices / Lemon myrtle",
"Herbs & Spices / Lemon verbena",
"Herbs & Spices / Lemongrass",
"Herbs & Spices / Leptotes bicolor",
"Herbs & Spices / Lesser calamint , nipitella, nepitella",
"Herbs & Spices / Licorice, liquorice",
"Herbs & Spices / Lime flower, linden flower",
"Herbs & Spices / Lovage",
"Herbs & Spices / Mace",
"Herbs & Spices / Mahlab, St. Lucie cherry",
"Herbs & Spices / Malabathrum, tejpat",
"Herbs & Spices / Marjoram",
"Herbs & Spices / Marsh mallow",
"Herbs & Spices / Mastic",
"Herbs & Spices / Mint",
"Herbs & Spices / Mountain horopito",
"Herbs & Spices / Musk mallow, abelmosk",
"Herbs & Spices / Mustard / Black mustard",
"Herbs & Spices / Mustard / Brown mustard",
"Herbs & Spices / Mustard / Yellow mustard",
"Herbs & Spices / Mustard / White mustard",
"Herbs & Spices / Mustard / Mustard seeds",
"Herbs & Spices / Nasturtium",
"Herbs & Spices / Nigella, kalonji, black caraway, black onion seed",
"Herbs & Spices / Njangsa, djansang",
"Herbs & Spices / Nutmeg",
"Herbs & Spices / Nutmeg",
"Herbs & Spices / Olida",
"Herbs & Spices / Onion powder",
"Herbs & Spices / Oregano",
"Herbs & Spices / Orris root",
"Herbs & Spices / Pandan flower, kewra",
"Herbs & Spices / Pandan leaf, screwpine",
"Herbs & Spices / Pandanus amaryllifolius",
"Herbs & Spices / Paprika",
"Herbs & Spices / Paracress",
"Herbs & Spices / Parsley",
"Herbs & Spices / Pepper / Black pepper",
"Herbs & Spices / Pepper / Chili pepper / Jalapeno pepper",
"Herbs & Spices / Pepper / Chili pepper / Habanero pepper",
"Herbs & Spices / Pepper / Chili pepper / Paprika pepper",
"Herbs & Spices / Pepper / Chili pepper / Tabasco pepper",
"Herbs & Spices / Pepper / Chili pepper / Cayenne pepper",
"Herbs & Spices / Pepper / Cubeb pepper",
"Herbs & Spices / Pepper / Green pepper",
"Herbs & Spices / Pepper / Kani pepper",
"Herbs & Spices / Pepper / Peruvian pepper",
"Herbs & Spices / Pepper / Pink pepper",
"Herbs & Spices / Pepper / Red pepper",
"Herbs & Spices / Pepper / Szechuan pepper",
"Herbs & Spices / Pepper / White pepper",
"Herbs & Spices / Peppercorns",
"Herbs & Spices / Peppermint",
"Herbs & Spices / Perilla, shiso",
"Herbs & Spices / Poppy seeds",
"Herbs & Spices / Quassia",
"Herbs & Spices / Ramsons, wood garlic",
"Herbs & Spices / Rice paddy herb",
"Herbs & Spices / Rosemary",
"Herbs & Spices / Rue",
"Herbs & Spices / Safflower",
"Herbs & Spices / Saffron",
"Herbs & Spices / Sage",
"Herbs & Spices / Saigon cinnamon",
"Herbs & Spices / Salad burnet",
"Herbs & Spices / Salep",
"Herbs & Spices / Salt",
"Herbs & Spices / Sassafras",
"Herbs & Spices / Sesame seeds",
"Herbs & Spices / Silphium, silphion, laser, laserpicium, lasarpicium",
"Herbs & Spices / Sorrel",
"Herbs & Spices / Spearmint",
"Herbs & Spices / Spikenard",
"Herbs & Spices / Star anise",
"Herbs & Spices / Sumac",
"Herbs & Spices / Sweet woodruff",
"Herbs & Spices / Tarragon",
"Herbs & Spices / Thyme",
"Herbs & Spices / Turmeric",
"Herbs & Spices / Turmeric",
"Herbs & Spices / Turmeric",
"Herbs & Spices / Vanilla",
"Herbs & Spices / Vanilla extract",
"Herbs & Spices / Wasabi",
"Herbs & Spices / Watercress",
"Herbs & Spices / Wattleseed",
"Herbs & Spices / Wild betel",
"Herbs & Spices / Wild thyme",
"Herbs & Spices / Willow herb",
"Herbs & Spices / Winter savory",
"Herbs & Spices / Wintergreen",
"Herbs & Spices / Wood avens, herb bennet",
"Herbs & Spices / Woodruff",
"Herbs & Spices / Wormwood, absinthe",
"Herbs & Spices / Yerba buena",
"Herbs & Spices / Za'atar",
"Herbs & Spices / Zedoary",
"Cereal Grains / Rice / Basmati Rice",
"Cereal Grains / Rice / Black Rice",
"Cereal Grains / Rice / Broken Rice",
"Cereal Grains / Rice / Brown Rice",
"Cereal Grains / Rice / Jasmine Rice",
"Cereal Grains / Rice / Organic Rice",
"Cereal Grains / Rice / White Corn",
"Cereal Grains / Rice / Wild rice",
"Cereal Grains / Rice / Yellow Corn",
"Cereal Grains / Amaranth",
"Cereal Grains / Bamboo shoots",
"Cereal Grains / Barley",
"Cereal Grains / Barleygrass",
"Cereal Grains / Breadnut",
"Cereal Grains / Buckwheat",
"Cereal Grains / Bulgur wheat",
"Cereal Grains / Cattail",
"Cereal Grains / Chia",
"Cereal Grains / Cornbread",
"Cereal Grains / Cornmeal",
"Cereal Grains / Couscous",
"Cereal Grains / Crackers",
"Cereal Grains / Durum wheat",
"Cereal Grains / Farro, Emmer",
"Cereal Grains / Flax",
"Cereal Grains / Flaxseed",
"Cereal Grains / Fonio",
"Cereal Grains / Grano",
"Cereal Grains / Grits",
"Cereal Grains / Kamut grain",
"Cereal Grains / Kaniwa",
"Cereal Grains / Lemongrass, citronella",
"Cereal Grains / Millet",
"Cereal Grains / Molasses",
"Cereal Grains / Muesli, Breakfast cereal, Granola",
"Cereal Grains / Noodles",
"Cereal Grains / Oatmeal",
"Cereal Grains / Oats",
"Cereal Grains / Other Grain",
"Cereal Grains / Palmer's grass",
"Cereal Grains / Pearl Millet",
"Cereal Grains / Pitseed Goosefoot ",
"Cereal Grains / Popcorn",
"Cereal Grains / Quinoa ",
"Cereal Grains / Rapadura",
"Cereal Grains / Rye",
"Cereal Grains / Semolina wheat",
"Cereal Grains / Sorghum",
"Cereal Grains / Spelt ",
"Cereal Grains / Teff",
"Cereal Grains / Triticale",
"Cereal Grains / Wattleseed, Acacia seed",
"Cereal Grains / Wheat ",
"Cereal Grains / Wheat Berries",
"Cereal Grains / Wheatgrass ",
"Cereal Grains / Flour / White flour",
"Cereal Grains / Flour / Brown flour",
"Cereal Grains / Flour / Rye flour",
"Cereal Grains / Flour / Spelt flour",
"Cereal Grains / Flour / Barley flour",
"Pasta / Minute pasta",
"Pasta / Long Noodles",
"Pasta / Ribbon-Cut Noodles",
"Pasta / Decorative Shaped Pasta",
"Pasta / Stuffed pasta",
"Drinks / Juice / Apple juice",
"Drinks / Juice / Orange juice",
"Drinks / Juice / Pear juice",
"Drinks / Juice / Grape juice",
"Drinks / Soft drinks / Ginger Beer",
"Drinks / Soft drinks / Lemonade",
"Drinks / Alcoholic drinks / Beer / Ale / Barleywine",
"Drinks / Alcoholic drinks / Beer / Ale / Bitter ale",
"Drinks / Alcoholic drinks / Beer / Ale / Mild ale",
"Drinks / Alcoholic drinks / Beer / Ale / Pale ale",
"Drinks / Alcoholic drinks / Beer / Ale / Porter / Stout",
"Drinks / Alcoholic drinks / Beer / Ale / Cask ale",
"Drinks / Alcoholic drinks / Beer / Ale / Stock ale",
"Drinks / Alcoholic drinks / Beer / Fruit Beer",
"Drinks / Alcoholic drinks / Beer / Large Beer / Bock",
"Drinks / Alcoholic drinks / Beer / Large Beer / Dry beer",
"Drinks / Alcoholic drinks / Beer / Large Beer / Maerzen/Oktoberfest Beer",
"Drinks / Alcoholic drinks / Beer / Large Beer / Pilsener",
"Drinks / Alcoholic drinks / Beer / Large Beer / Schwarzbier",
"Drinks / Alcoholic drinks / Beer / Sahti",
"Drinks / Alcoholic drinks / Beer / Small beer",
"Drinks / Alcoholic drinks / Beer / Wheat beer / Witbier White Beer",
"Drinks / Alcoholic drinks / Beer / Wheat beer / Hefeweizen",
"Drinks / Alcoholic drinks / Cauim",
"Drinks / Alcoholic drinks / Chicha",
"Drinks / Alcoholic drinks / Cider   ",
"Drinks / Alcoholic drinks / Mead",
"Drinks / Alcoholic drinks / Palm wine",
"Drinks / Alcoholic drinks / Perry  ",
"Drinks / Alcoholic drinks / Sake    ",
"Drinks / Alcoholic drinks / Wine / Fruit wine",
"Drinks / Alcoholic drinks / Wine / Table wine",
"Drinks / Alcoholic drinks / Wine / Sangria",
"Drinks / Alcoholic drinks / Wine / Sparkling wine / Champagne",
"Drinks / Alcoholic drinks / Wine / Fortified wine / Port",
"Drinks / Alcoholic drinks / Wine / Fortified wine / Madeira",
"Drinks / Alcoholic drinks / Wine / Fortified wine / Marsala",
"Drinks / Alcoholic drinks / Wine / Fortified wine / Sherry",
"Drinks / Alcoholic drinks / Wine / Fortified wine / Vermouth",
"Drinks / Alcoholic drinks / Wine / Fortified wine / Vinsanto",
"Drinks / Alcoholic drinks / Spirits / Absinthe",
"Drinks / Alcoholic drinks / Spirits / Akvavit",
"Drinks / Alcoholic drinks / Spirits / Arak",
"Drinks / Alcoholic drinks / Spirits / Arrack",
"Drinks / Alcoholic drinks / Spirits / Baijiu",
"Drinks / Alcoholic drinks / Spirits / Cachaca",
"Drinks / Alcoholic drinks / Spirits / Gin / Damson gin",
"Drinks / Alcoholic drinks / Spirits / Gin / Sloe gin",
"Drinks / Alcoholic drinks / Spirits / Gulu",
"Drinks / Alcoholic drinks / Spirits / Horilka",
"Drinks / Alcoholic drinks / Spirits / Kaoliang",
"Drinks / Alcoholic drinks / Spirits / Maotai",
"Drinks / Alcoholic drinks / Spirits / Mezcal",
"Drinks / Alcoholic drinks / Spirits / Neutral grain spirit",
"Drinks / Alcoholic drinks / Spirits / Ogogoro",
"Drinks / Alcoholic drinks / Spirits / Ouzo",
"Drinks / Alcoholic drinks / Spirits / Palinka",
"Drinks / Alcoholic drinks / Spirits / Pisco ",
"Drinks / Alcoholic drinks / Spirits / Rum",
"Drinks / Alcoholic drinks / Spirits / Soju",
"Drinks / Alcoholic drinks / Spirits / Tequila",
"Drinks / Alcoholic drinks / Spirits / Vodka",
"Drinks / Alcoholic drinks / Spirits / Metaxa",
"Drinks / Alcoholic drinks / Spirits / Whisky / Bourbon",
"Drinks / Alcoholic drinks / Spirits / Whisky / Scotch",
"Drinks / Alcoholic drinks / Spirits / Whisky / Tennessee whiskey",
"Drinks / Alcoholic drinks / Spirits / Brandy / Armagnac",
"Drinks / Alcoholic drinks / Spirits / Brandy / Cognac",
"Drinks / Alcoholic drinks / Spirits / Brandy / Fruit brandy, Eau-de-vie, Schnapps",
"Drinks / Alcoholic drinks / Spirits / Brandy / Kirsch",
"Drinks / Tea / Green",
"Drinks / Tea / Black",
"Drinks / Tea / Herbal",
"Drinks / Coffee ",
"Convenience foods, processed foods / Baby Food",
"Convenience foods, processed foods / Crisps",
"Convenience foods, processed foods / Energy bars",
"Convenience foods, processed foods / Ready meals",
"Convenience foods, processed foods / Soup",
"Sweeteners, confection / Agave nectar",
"Sweeteners, confection / Barley malt syrup",
"Sweeteners, confection / Birch syrup",
"Sweeteners, confection / Brown sugar",
"Sweeteners, confection / Cane sugar",
"Sweeteners, confection / Chocolate",
"Sweeteners, confection / Honey",
"Sweeteners, confection / Maple syrup",
"Sweeteners, confection / Marshmallows",
"Sweeteners, confection / Molasses",
"Sweeteners, confection / Palm sugar",
"Sweeteners, confection / Shredded coconut",
"Sweeteners, confection / Sorghum Syrup",
"Sweeteners, confection / Sugar (beet)",
"Sweeteners, confection / Sugar (cane)",
"Sweeteners, confection / Sugar substitutes",
"Sweeteners, confection / Syrup",
"Sweeteners, confection / White sugar",
"Baked goods / Biscuits, cookies",
"Baked goods / Breads / Flatbreads",
"Baked goods / Breads / Sourdough bread",
"Baked goods / Breads / Rye bread",
"Baked goods / Breads / Spelt bread",
"Baked goods / Breads / Granary bread",
"Baked goods / Cakes / Cake mixes",
"Baked goods / Pastry",
"Baked goods / Pies",
"Baked goods / Twice-baked goods / Biscotti",
"Baked goods / Twice-baked goods / Rusk",
"Baked goods / Twice-baked goods / Zweiback",
"Processed fats and oils / Refined oils",
"Processed fats and oils / Cooking spray",
"Processed fats and oils / Margarine",
"Processed fats and oils / Salad dressing",
"Processed fats and oils / BBQ sauce",
"Processed fats and oils / Mustard",
"Processed fats and oils / Ketchup",
"Processed fats and oils / Mayonnaise",
"Processed fats and oils / Peanut butter",
"Preserves / Chutneys, Pickles",
"Preserves / Jam, Marmaladae",
"Preserves / Pesto"]

final_foods = [{'node': 'Meat', 'children': ['Beef', 'Bison', 'Buffalo', 'Chicken', 'Duck', 'Geese / goose', 'Lamb', 'Mutton', 'Ostrich', 'Pork', 'Turkey', 'Veal', 'Game / Partridge', 'Game / Pheasant', 'Game / Rabbit', 'Game / Hare / levret', 'Game / Venison', 'Processed meat / Bacon', 'Processed meat / Burgers', 'Processed meat / Cured meat', 'Processed meat / Gelatins', 'Processed meat / Haggis', 'Processed meat / Ham', 'Processed meat / Lunch meat', 'Processed meat / Meat Pies', 'Processed meat / Meatballs / Faggots', 'Processed meat / Mincemeat', 'Processed meat / Pasties', 'Processed meat / Pate', 'Processed meat / Pork Pies', 'Processed meat / Sausages', 'Processed meat / Scotch Eggs', 'Processed meat / Smoked Duck / Chicken', 'Processed meat / Spiced Chicken']}, {'node': 'Fish', 'children': ['Bass', 'Bream', 'Cod', 'Haddock', 'Mackerel', 'Salmon', 'Trout', 'Salmon', 'Mackerel', 'Trout', 'American Shad', 'American Sole', 'Anchovy', 'Antarctic Cod', 'Arrowtooth Eel', 'Asian Carps', 'Atka Mackerel', 'Atlantic Bonito', 'Atlantic Cod', 'Atlantic Eel', 'Atlantic Herring', 'Atlantic Salmon', 'Atlantic Trout', 'Australasian Salmon', 'Bar Jack', 'Bat Fish', 'Barramundi', 'Basa Fish', 'Black Mackerel', 'Blue Cod', 'Bluegill', 'Bluefish', 'Bombay Duck', 'Brook Trout', 'Butterfish', 'California Halibut', 'California Sheephead', 'Capelin', 'Carp', 'Catfish', 'Cherry Salmon', 'Chinook Salmon', 'Chum Salmon', 'Cobia', 'Cod', 'Coho Salmon', 'Coley', 'Common Carp', 'Crappie', 'Crawfish', 'Dory', 'Discus', 'Drum', 'Dino', 'Eel', 'European Eel', 'European Flounder', 'Flathead', 'Flatfish', 'Flounder', 'Freshwater Eel', 'Freshwater Herring', 'Flying Fish', 'Giant Gourami', 'Gilt-head Bream', 'Golden Dorado', 'Groundfish', 'Grouper', 'Gar', 'Haddock', 'Hake', 'Halibut', 'Harvestfish', 'Herring', 'Hilsa', 'Hoki', 'Iridescent Shark / Basa Fish', 'Japanese Butterfish', 'John Dory', 'Kapenta', 'Kingklip', 'Lemon Sole', 'Largemouth Bass', 'Mackerel', 'Maori Cod', 'Mahi-mahi', 'Marlin', 'Milkfish', 'Monkfish', 'Mullet', 'Mullus Surmuletus', 'Northern Anchovy', 'Northern Pike', 'Northern Snakehead', 'Norwegian Atlantic Salmon', 'Orange Roughy', 'Oscar', 'Pacific Herring', 'Pacific Salmon', 'Pacific Saury', 'Pacific Trout', 'Panfish', 'Pangasius', 'Patagonian Toothfish', 'Pelagic Cod', 'Perch', 'Pink Salmon', 'Pollock', 'Pomfret', 'Pilchard', 'Paddlefish', 'Plaice', 'Pacific Cod', 'Quoy Fish', 'Rainbow Trout', 'Redfish', 'Red Snapper', 'Rock Fish', 'Round Herring', 'Salmon', 'Sardine', 'Saury', 'Scrod', 'Sea Bass', 'Seer Fish', 'Shad', 'Shrimpfish', 'Silver Carp', 'Skipjack Tuna', 'Slender Rainbow Sardine', 'Sole', 'Snakeskin Gourami', 'Snapper', 'Snook', 'Snoek', 'Spanish Mackerel', 'Surf Sardine', 'Swamp-eel', 'Swordfish', 'Skate', 'Sunfish  Bluegill', 'Smallmouth Bass', 'Spoonbill / Paddlefish', 'Thresher Shark', 'Tilapia', 'Tilefish', 'Trout', 'Tuna', 'Turbot', 'Yellowfin Tuna', 'Zander', 'Caviar', 'Roe (cod)', 'Processed Fish / Fishcakes', 'Processed Fish / Fishpie', 'Processed Fish / Fishfingers', 'Processed Fish / Sushi']}, {'node': 'Shellfish', 'children': ['Prawns', 'Oysters', 'Lobster', 'Clams', 'Crabs', 'Shrimp', 'Cockles', 'Mussels', 'Scallops', 'Whelks', 'Winkles']}, {'node': 'Dairy', 'children': ['Butter', 'Cream / Clotted cream', 'Cream / Single cream', 'Cream / Double cream', "Milk / Cow's milk", "Milk / Goat's milk", 'Cheese / Chedder', 'Cheese / Goat', 'Cheese / Brie', 'Cheese / Stilton', 'Cheese /', 'Cheese / Blue cheese / Bath Blue cheese', 'Cheese / Blue cheese / Barkham Blue cheese', 'Cheese / Blue cheese / Blue Monday cheese', 'Cheese / Blue cheese / Buxton Blue cheese', 'Cheese / Blue cheese / Cheshire Blue cheese', 'Cheese / Blue cheese / Devon Blue cheese', 'Cheese / Blue cheese / Dorset Blue Vinney cheese', 'Cheese / Blue cheese / Dovedale cheese', 'Cheese / Blue cheese / Exmoor Blue cheese', 'Cheese / Blue cheese / Harbourne Blue cheese', 'Cheese / Blue cheese / Lanark Blue  cheese', 'Cheese / Blue cheese / Oxford Blue cheese', 'Cheese / Blue cheese / Shropshire Blue cheese', 'Cheese / Blue cheese / Stichelton cheese', 'Cheese / Blue cheese / Stilton cheese', 'Cheese / Blue cheese / Blue Wensleydale cheese', 'Cheese / Blue cheese / Yorkshire Blue cheese', 'Cheese / Appledore cheese', 'Cheese / Berkswell cheese', 'Cheese / Bonchester cheese', 'Cheese / Brie cheese', 'Cheese / Somerset Brie', 'Cheese / Cornish Brie cheese', 'Cheese / Brinkburn cheese', 'Cheese / Caithness cheese', 'Cheese / Caboc cheese', 'Cheese / Caerphilly cheese', 'Cheese / Cheddar cheese', 'Cheese / West Country Farmhouse Cheddar cheese', 'Cheese / Applewood cheese', 'Cheese / Coleraine Cheddar cheese', 'Cheese / Cheshire cheese', 'Cheese / Appleby Cheshire cheese', 'Cheese / Chevington cheese', 'Cheese / Coquetdale cheese', 'Cheese / Cornish Pepper cheese', 'Cheese / Cotherstone cheese', 'Cheese / Cotswold cheese', 'Cheese / Coverdale cheese', 'Cheese / Croglin cheese', 'Cheese / Crowdie cheese', 'Cheese / Derby cheese', 'Cheese / Double Gloucester cheese', 'Cheese / Goosnargh Gold cheese', 'Cheese / Dorstone cheese', 'Cheese / Dovedale cheese', 'Cheese / Farmhouse Llanboidy cheese', 'Cheese / Fine Fettle Yorkshire cheese', 'Cheese / Black Eyed Susan cheese', 'Cheese / Golden Cross cheese', 'Cheese / Gruth Dhu cheese', 'Cheese / Harlech cheese', 'Cheese / Hereford Hop cheese', 'Cheese / Huntsman cheese', 'Cheese / Ilchester cheese', 'Cheese / Innkeepers Choice cheese', 'Cheese / Isle Of Mull cheese', 'Cheese / Lancashire cheese', 'Cheese / Beacon Fell Traditional Lancashire cheese', 'Cheese / Lincolnshire Poacher cheese', 'Cheese / Little Wallop cheese', "Cheese / Katy's White Lavender cheese", 'Cheese / Kidderton Ash cheese', 'Cheese / Lord Of The Hundreds cheese', 'Cheese / Lowerdale Goats Cheese cheese', 'Cheese / Pantysgawn cheese', 'Cheese / Red Devil cheese', 'Cheese / Red Dragon cheese', 'Cheese / Red Leicester cheese', 'Cheese / Rothbury Red cheese', 'Cheese / Red Windsor cheese', 'Cheese / Sage Derby cheese', 'Cheese / Single Gloucester cheese', 'Cheese / Stinking Bishop cheese', 'Cheese / Sussex Slipcote cheese', 'Cheese / Swaledale cheese', 'Cheese / Teviotdale  cheese', 'Cheese / Tintern cheese', 'Cheese / Waterloo cheese', 'Cheese / Wensleydale cheese', 'Cheese / White Stilton cheese', 'Cheese / Suffolk Gold cheese', 'Cheese / Whitehaven cheese', 'Cheese / Yarg cheese', 'Cheese / Wild Garlic Yarg cheese', 'Cheese / Wiltshire Loaf', 'Cheese / Woolsery Goats cheese', 'Cheese / Village Green Goat', 'Cheese / Y Fenni cheese', 'Ice Cream / Sorbets', 'Yoghurt']}, {'node': 'Eggs', 'children': ['Chicken', 'Duck', 'Quails', 'Goose / geese', 'Turkey']}, {'node': 'Fruit', 'children': ['Apples   ', 'Apricots', 'Bananas', 'Bilberry', 'Blackberries', 'Blackcurrants', 'Blueberries', 'Cherimoya', 'Cherries', 'Clementine', 'Coconuts', 'Cranberries', 'Currant', 'Damson', 'Dates', 'Dragon fruit', 'Durians ', 'Elderberry', 'Feijoa', 'Fig', 'Gooseberries', 'Gooseberry', 'Grape', 'Grapefruit', 'Grapes', 'Guava', 'Honeydew melon', 'Huckleberry', 'Jack fruit ', 'Jambul', 'Kiwi fruit', 'Kumquat', 'Legume', 'Lemon  ', 'Limes', 'Lychee', 'Mandarine', 'Mango  ', 'Mangostine', 'Medlar', 'Melon / cantaloupe', 'Nectarines', 'Oranges', 'Papaya', 'Peach', 'Pears', 'Physalis', 'Pineapple', 'Pitaya', 'Plum, prune', 'Pomegranates', 'Prunes', 'Quince ', 'Raisins', 'Rambutan', 'Raspberries ', 'Redcurrants', 'Rhubarb', 'Salal berry', 'Satsuma', 'Star fruit', 'Strawberries ', 'Tangerines', 'Ugli fruit ', 'Watermelon  ', 'Processed fruits / Canned fruit', 'Processed fruits / Frozen fruit', 'Processed fruits / Fruit sauces', 'Processed fruits / Jam', 'Processed fruits / Pie fillings']}, {'node': 'Vegetables', 'children': ['Artichokes / Jerusalem', 'Artichokes / Globe ', 'Aubergine', 'Alfalfa sprouts', 'Anise', 'Artichoke', 'Arugula', 'Asparagus', 'Aubergine, Eggplant', 'Avocados ', 'Beansprouts', 'Bell pepper', 'Beetroot, Beet', 'Breadfruit', 'Broccoflower ', 'Broccoli / Purple Sprouting Broccoli', 'Brussels sprouts', 'Cabbage / Red', 'Cabbage / White', 'Cabbage / Green ', 'Calabrese ', 'Celeriac', 'Chinese leaves, Bok choy', 'Collard greens', 'Corn salad', 'Carrots', 'Cauliflflower', 'Celery', 'Chard ', 'Cucumbers ', 'Crimini', 'Daikon', 'Endive', 'Fennel ', 'Fiddlehead fern', 'Frisee leaves', 'Garlic', 'Jicama', 'Kale / Curly kale', 'Kale / Mixed kale', 'Kohlrabi', 'Leeks', 'Lettuce / Romaine', 'Lettuce / Iceberg', 'Marrow', 'Mushrooms / Shiitake mushrooms', 'Mushrooms / Truffles', 'Mushrooms / Boletus mushrooms', 'Mushrooms / Oyster mushrooms', 'Mushrooms / Wild mushrooms', 'Mushrooms / Button mushrooms', 'Mustard greens', 'Nettles ', 'Okra', 'Olives', 'Onions', 'Pakchoi', 'Parsnips', 'Potatoes / Charlotte potatoes', 'Potatoes / King Edward potatoes', 'Potatoes / Estima potatoes', 'Potatoes / Maris Piper potatoes', 'Potatoes / Desiree potatoes', 'Potatoes / Marfona potatoes', 'Potatoes / Anya potatoes', 'Potatoes / Nicola potatoes', 'Potatoes / Rooster potatoes', 'Potatoes / Sante potatoes', 'Potatoes / Accord potatoes', 'Potatoes / Carlingford potatoes', 'Potatoes / Romano potatoes', 'Potatoes / Sweet potatoes, yams', 'Rocket', 'Radicchio', 'Radish', 'Rhubarb', 'Salad', 'Salad Packs', 'Salsify ', 'Savoy Cabbage', 'Sea Vegetables ', 'Shallots', 'Skirret ', 'Spinach', 'Spring Greens ', 'Spring onions, Green onion, Scallion', 'Sprouted Seeds ', 'Squashes / Acorn squash', 'Squashes / Butternut squash', 'Squashes / Courgette, Zucchini', 'Squashes / Cucumber ', 'Squashes / Gem squash', 'Squashes / Marrow, Squash', 'Squashes / Pumpkin', 'Squashes / Spaghetti squash', 'Swede, Rutabaga', 'Sweetcorn, maize, corn', 'Swiss Chard', 'Taro ', 'Tat soi', 'Tomatoes', 'Turnips', 'Turnip Greens ', 'Watercress  ', 'Wasabi', 'Water chestnut', 'White radish', 'Processed vegetables / Canned vegetables', 'Processed vegetables / Frozen vegetables', 'Processed vegetables / French fries']}, {'node': 'Beans & Legumes', 'children': ['Azuki beans, Adzuki beans', 'Bean sprouts', 'Black beans', 'Black-eyed peas', 'Borlotti beans', 'Broad beans', 'Butter Beans', 'Chickpeas, Garbanzo beans, Ceci beans', 'Dried Peas', 'Green beans', 'Kidney beans', 'Lentils', 'Lima bean, Butter bean', 'Miso', 'Mung beans', 'Navy beans', 'Peas / Mangetout, Sugar snap peas', 'Pinto beans', 'Runner beans', 'Soy beans', 'Soybeans', 'Tempeh', 'Tofu', 'Vigna Beans']}, {'node': 'Nuts, Seeds & Oils', 'children': ['Almonds', 'Apricot Kernels', 'Betel Nuts', 'Brazil Nuts', 'Cashews', 'Chestnuts', 'Flaxseeds', 'Ginkgo Nuts', 'Hazelnuts', 'Macadamia Nuts', 'Melon Seeds', 'Olive Oil', 'Peanuts', 'Pecan Nuts', 'Pine Nuts', 'Pistachio Nuts', 'Pumpkin Seeds', 'Sesame Seeds', 'Sunflower Kernels', 'Sunflower Seeds', 'Walnuts']}, {'node': 'Herbs & Spices', 'children': ['Ajwain, carom seeds', 'Akudjura', 'Alexanders', 'Allspice', 'Angelica', 'Anise', 'Aniseed myrtle', 'Annatto', 'Apple mint', 'Arrowroot starch', 'Avocado leaf', 'Barberry', 'Basil', 'Bay leaf', 'Black cardamom', 'Boldo', 'Borage', 'Calendula, pot marigold', 'Camphor laurel', 'Caraway', 'Cardamom', 'Carob', 'Cassia', 'Catnip', 'Celery seed', 'Chervil', 'Chicory', 'Chili powder', 'Chives', 'Cicely', 'Cilantro, coriander greens, coriander herb', 'Cinnamon', 'Cinnamon myrtle', 'Clary, Clary sage', 'Cloves', 'Coriander', 'Coriander seed', 'Costmary', 'Cream of tartar', 'Cudweed', 'Cumin', 'Cumin Seeds', 'Curry leaf', 'Curry plant', 'Curry powder', 'Dill', 'Dill seed', 'Elderflower', 'Epazote', 'Fennel', 'Fennel seeds', 'Fenugreek', 'File powder, gumbo file', 'Fingerroot, krachai, temu kuntji', 'Five-spice powder ', 'Galingale', 'Garlic / Garlic powder', 'Garlic / Elephant garlic', 'Garlic chives', 'Ginger', 'Golpar, Persian hogweed', 'Grains of paradise', 'Horseradish', 'Houttuynia cordata', 'Huacatay, Mexican marigold, mint marigold', 'Hyssop', 'Jasmine flowers', 'Jimbu', 'Juniper berry', 'Kaffir lime leaves, Makrud lime leaves', 'Kala zeera , black cumin', 'Kawakawa seeds', 'Keluak, kluwak, kepayang', 'Kencur, galangal, kentjur', 'Kokam seed', 'Korarima, Ethiopian cardamom, false cardamon', 'Koseret leaves', 'Lavender', 'Lemon balm', 'Lemon ironbark', 'Lemon myrtle', 'Lemon verbena', 'Lemongrass', 'Leptotes bicolor', 'Lesser calamint , nipitella, nepitella', 'Licorice, liquorice', 'Lime flower, linden flower', 'Lovage', 'Mace', 'Mahlab, St. Lucie cherry', 'Malabathrum, tejpat', 'Marjoram', 'Marsh mallow', 'Mastic', 'Mint', 'Mountain horopito', 'Musk mallow, abelmosk', 'Mustard / Black mustard', 'Mustard / Brown mustard', 'Mustard / Yellow mustard', 'Mustard / White mustard', 'Mustard / Mustard seeds', 'Nasturtium', 'Nigella, kalonji, black caraway, black onion seed', 'Njangsa, djansang', 'Nutmeg', 'Nutmeg', 'Olida', 'Onion powder', 'Oregano', 'Orris root', 'Pandan flower, kewra', 'Pandan leaf, screwpine', 'Pandanus amaryllifolius', 'Paprika', 'Paracress', 'Parsley', 'Pepper / Black pepper', 'Pepper / Chili pepper / Jalapeno pepper', 'Pepper / Chili pepper / Habanero pepper', 'Pepper / Chili pepper / Paprika pepper', 'Pepper / Chili pepper / Tabasco pepper', 'Pepper / Chili pepper / Cayenne pepper', 'Pepper / Cubeb pepper', 'Pepper / Green pepper', 'Pepper / Kani pepper', 'Pepper / Peruvian pepper', 'Pepper / Pink pepper', 'Pepper / Red pepper', 'Pepper / Szechuan pepper', 'Pepper / White pepper', 'Peppercorns', 'Peppermint', 'Perilla, shiso', 'Poppy seeds', 'Quassia', 'Ramsons, wood garlic', 'Rice paddy herb', 'Rosemary', 'Rue', 'Safflower', 'Saffron', 'Sage', 'Saigon cinnamon', 'Salad burnet', 'Salep', 'Salt', 'Sassafras', 'Sesame seeds', 'Silphium, silphion, laser, laserpicium, lasarpicium', 'Sorrel', 'Spearmint', 'Spikenard', 'Star anise', 'Sumac', 'Sweet woodruff', 'Tarragon', 'Thyme', 'Turmeric', 'Turmeric', 'Turmeric', 'Vanilla', 'Vanilla extract', 'Wasabi', 'Watercress', 'Wattleseed', 'Wild betel', 'Wild thyme', 'Willow herb', 'Winter savory', 'Wintergreen', 'Wood avens, herb bennet', 'Woodruff', 'Wormwood, absinthe', 'Yerba buena', "Za'atar", 'Zedoary']}, {'node': 'Cereal Grains', 'children': ['Rice / Basmati Rice', 'Rice / Black Rice', 'Rice / Broken Rice', 'Rice / Brown Rice', 'Rice / Jasmine Rice', 'Rice / Organic Rice', 'Rice / White Corn', 'Rice / Wild rice', 'Rice / Yellow Corn', 'Amaranth', 'Bamboo shoots', 'Barley', 'Barleygrass', 'Breadnut', 'Buckwheat', 'Bulgur wheat', 'Cattail', 'Chia', 'Cornbread', 'Cornmeal', 'Couscous', 'Crackers', 'Durum wheat', 'Farro, Emmer', 'Flax', 'Flaxseed', 'Fonio', 'Grano', 'Grits', 'Kamut grain', 'Kaniwa', 'Lemongrass, citronella', 'Millet', 'Molasses', 'Muesli, Breakfast cereal, Granola', 'Noodles', 'Oatmeal', 'Oats', 'Other Grain', "Palmer's grass", 'Pearl Millet', 'Pitseed Goosefoot ', 'Popcorn', 'Quinoa ', 'Rapadura', 'Rye', 'Semolina wheat', 'Sorghum', 'Spelt ', 'Teff', 'Triticale', 'Wattleseed, Acacia seed', 'Wheat ', 'Wheat Berries', 'Wheatgrass ', 'Flour / White flour', 'Flour / Brown flour', 'Flour / Rye flour', 'Flour / Spelt flour', 'Flour / Barley flour']}, {'node': 'Pasta', 'children': ['Minute pasta', 'Long Noodles', 'Ribbon-Cut Noodles', 'Decorative Shaped Pasta', 'Stuffed pasta']}, {'node': 'Drinks', 'children': ['Juice / Apple juice', 'Juice / Orange juice', 'Juice / Pear juice', 'Juice / Grape juice', 'Soft drinks / Ginger Beer', 'Soft drinks / Lemonade', 'Alcoholic drinks / Beer / Ale / Barleywine', 'Alcoholic drinks / Beer / Ale / Bitter ale', 'Alcoholic drinks / Beer / Ale / Mild ale', 'Alcoholic drinks / Beer / Ale / Pale ale', 'Alcoholic drinks / Beer / Ale / Porter / Stout', 'Alcoholic drinks / Beer / Ale / Cask ale', 'Alcoholic drinks / Beer / Ale / Stock ale', 'Alcoholic drinks / Beer / Fruit Beer', 'Alcoholic drinks / Beer / Large Beer / Bock', 'Alcoholic drinks / Beer / Large Beer / Dry beer', 'Alcoholic drinks / Beer / Large Beer / Maerzen/Oktoberfest Beer', 'Alcoholic drinks / Beer / Large Beer / Pilsener', 'Alcoholic drinks / Beer / Large Beer / Schwarzbier', 'Alcoholic drinks / Beer / Sahti', 'Alcoholic drinks / Beer / Small beer', 'Alcoholic drinks / Beer / Wheat beer / Witbier White Beer', 'Alcoholic drinks / Beer / Wheat beer / Hefeweizen', 'Alcoholic drinks / Cauim', 'Alcoholic drinks / Chicha', 'Alcoholic drinks / Cider   ', 'Alcoholic drinks / Mead', 'Alcoholic drinks / Palm wine', 'Alcoholic drinks / Perry  ', 'Alcoholic drinks / Sake    ', 'Alcoholic drinks / Wine / Fruit wine', 'Alcoholic drinks / Wine / Table wine', 'Alcoholic drinks / Wine / Sangria', 'Alcoholic drinks / Wine / Sparkling wine / Champagne', 'Alcoholic drinks / Wine / Fortified wine / Port', 'Alcoholic drinks / Wine / Fortified wine / Madeira', 'Alcoholic drinks / Wine / Fortified wine / Marsala', 'Alcoholic drinks / Wine / Fortified wine / Sherry', 'Alcoholic drinks / Wine / Fortified wine / Vermouth', 'Alcoholic drinks / Wine / Fortified wine / Vinsanto', 'Alcoholic drinks / Spirits / Absinthe', 'Alcoholic drinks / Spirits / Akvavit', 'Alcoholic drinks / Spirits / Arak', 'Alcoholic drinks / Spirits / Arrack', 'Alcoholic drinks / Spirits / Baijiu', 'Alcoholic drinks / Spirits / Cachaca', 'Alcoholic drinks / Spirits / Gin / Damson gin', 'Alcoholic drinks / Spirits / Gin / Sloe gin', 'Alcoholic drinks / Spirits / Gulu', 'Alcoholic drinks / Spirits / Horilka', 'Alcoholic drinks / Spirits / Kaoliang', 'Alcoholic drinks / Spirits / Maotai', 'Alcoholic drinks / Spirits / Mezcal', 'Alcoholic drinks / Spirits / Neutral grain spirit', 'Alcoholic drinks / Spirits / Ogogoro', 'Alcoholic drinks / Spirits / Ouzo', 'Alcoholic drinks / Spirits / Palinka', 'Alcoholic drinks / Spirits / Pisco ', 'Alcoholic drinks / Spirits / Rum', 'Alcoholic drinks / Spirits / Soju', 'Alcoholic drinks / Spirits / Tequila', 'Alcoholic drinks / Spirits / Vodka', 'Alcoholic drinks / Spirits / Metaxa', 'Alcoholic drinks / Spirits / Whisky / Bourbon', 'Alcoholic drinks / Spirits / Whisky / Scotch', 'Alcoholic drinks / Spirits / Whisky / Tennessee whiskey', 'Alcoholic drinks / Spirits / Brandy / Armagnac', 'Alcoholic drinks / Spirits / Brandy / Cognac', 'Alcoholic drinks / Spirits / Brandy / Fruit brandy, Eau-de-vie, Schnapps', 'Alcoholic drinks / Spirits / Brandy / Kirsch', 'Tea / Green', 'Tea / Black', 'Tea / Herbal', 'Coffee ']}, {'node': 'Convenience foods, processed foods', 'children': ['Baby Food', 'Crisps', 'Energy bars', 'Ready meals', 'Soup']}, {'node': 'Sweeteners, confection', 'children': ['Agave nectar', 'Barley malt syrup', 'Birch syrup', 'Brown sugar', 'Cane sugar', 'Chocolate', 'Honey', 'Maple syrup', 'Marshmallows', 'Molasses', 'Palm sugar', 'Shredded coconut', 'Sorghum Syrup', 'Sugar (beet)', 'Sugar (cane)', 'Sugar substitutes', 'Syrup', 'White sugar']}, {'node': 'Baked goods', 'children': ['Biscuits, cookies', 'Breads / Flatbreads', 'Breads / Sourdough bread', 'Breads / Rye bread', 'Breads / Spelt bread', 'Breads / Granary bread', 'Cakes / Cake mixes', 'Pastry', 'Pies', 'Twice-baked goods / Biscotti', 'Twice-baked goods / Rusk', 'Twice-baked goods / Zweiback']}, {'node': 'Processed fats and oils', 'children': ['Refined oils', 'Cooking spray', 'Margarine', 'Salad dressing', 'BBQ sauce', 'Mustard', 'Ketchup', 'Mayonnaise', 'Peanut butter']}, {'node': 'Preserves', 'children': ['Chutneys, Pickles', 'Jam, Marmaladae', 'Pesto']}]

def process_foods(food_list):
    final_foods = []
    nodes = []
    for each in food_list:
        foo = each.split(" / ")
        nodes.append(foo[0]) if foo[0] not in nodes else 2

    for eachnode in nodes:
        children = []
        for each in food_list:
            foo = each.split(" / ")
            rem = foo[1:]
            rem = ' / '.join(rem)
            if foo[0] == eachnode:
                children.append(rem)
        final_foods.append({'node': eachnode, 'children': children})
    print final_foods
